### ISSUE TITLE
Very good job! When will the code of the paper be open source?

### ISSUE THREAD

**Issue by mymuli** [rmcong/GLNet_TCYB2022#1]
Very good job! 
When will the code of the paper be open source?

**Comment by rmcong** [comment]
Thanks for your attention. The source code and results have been released,
pls feel free to check them (https://github.com/rmcong/GLNet_TCYB2022).
-------------------------------------------------------------------------
Best regards,

Runmin Cong
Associate Professor
Beijing Jiaotong University (BJTU), Beijing, China
https://rmcong.github.io/



mymuli ***@***.***> 于2022年5月1日周日 16:27写道：

**Comment by mymuli** [comment]
Thank you very much!
